title: Running with Data
description: fun with data, music, and visualization
author: Jason Sundram
url: "https://runningwithdata.com" 
theme: jekyll-theme-dinky
# remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap        # Needs to be after other plugins that generate files.

